export const CREDENTIALS = {
  appKey: 'vtexappkey-pragma-RQPQAV',
  appToken:
    'DVKFWXNYDXABLPXPISHFATTVTFBPLEQUBDINNVOQOKOSAPQZUNDSOCHYSQHSUECFEWUHTLJTJBSZGWWVFYWCGZDSKMRTHQRWWWDOFWXHJPRXPAAUXNMGTUEKNJYPVNQD',
}
